In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from keras.models import load_model

In [2]:
MODEL = load_model("model.h5")

In [3]:
image_no = 0

In [4]:
input_img = cv2.imread('sample_images/image_{}.png'.format(image_no))
# input_img = cv2.imread('test_images/{}.jpg'.format(image_no))

In [5]:
print(input_img)
print(input_img.shape)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
(28, 28, 3)


In [6]:
gray = cv2.cvtColor(input_img,cv2.COLOR_BGR2GRAY)
print(gray.shape)

(28, 28)


In [7]:
image_resize = cv2.resize(gray,(28,28))
print(image_resize.shape)

(28, 28)


In [8]:
image_resize = image_resize/255
image_reshape = np.reshape(image_resize,[1,28,28,1])

In [9]:
prediction = MODEL.predict(image_reshape)
print(f"The Predicted digit is {np.argmax(prediction)}")

1/1 [==============================] - 0s 262ms/step
The Predicted digit is 0
